import type { Metadata } from "next";
import "./globals.css";
import { Scene } from "@/components/custom/scene";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-raleway'>
        <Scene />
        <main className="flex flex-col items-center justify-center w-full h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
